### DISCUSSION TITLE
Distrobox and host not sharing GPG keys correctly

### DISCUSSION THREAD

**Discussion by alexispurslane** [89luca89/distrobox#1419] [Q&A]
As the title states, I have a GPG key in my keyring on the host (as attested-to by `gpg --list-keys`), but when I'm in any of my distroxes (all msft devcontainers or similar) `gpg --list-keys` doesn't show anything, and if I create a key inside a distrobox, the host can't see that key. Example:

```bash
# on host
~ λ gpg --list-keys
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   2  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 2u
[keyboxd]
---------
pub   ed25519 2024-03-02 [SC]
      KEYID1
uid           [ultimate] Alexis Purslane (Github/Gitlab commit signing key) <alexispurslane@pm.me>

pub   ed25519 2024-05-27 [SC]
      KEYID2
uid           [ultimate] Alexis Purslane (New software forge signing key) <alexispurslane@pm.me>

# in a distrobox
@rust-latest /d/var/home/alexispurslane λ gpg --list-keys # neither key is visible
@rust-latest /d/var/home/alexispurslane λ gpg --full-generate-key # and if we make one in here...
...
gpg: revocation certificate stored as '/var/home/alexispurslane/.gnupg/openpgp-revocs.d/KEYID3.rev'
public and secret key created and signed.
...
pub   rsa3072 2024-05-27 [SC]
      KEYID3
uid                      Alexis Purslane (Stuck in distrobox key) <alexispurslane@pm.me>

# and go back to host...
~ λ gpg --list-keys # that key is not visible either
gpg: checking the trustdb
gpg: public key of ultimately trusted key EE192DA93B851775 not found
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   3  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 3u
[keyboxd]
---------
pub   ed25519 2024-03-02 [SC]
      KEYID1
uid           [ultimate] Alexis Purslane (Github/Gitlab commit signing key) <alexispurslane@pm.me>

pub   ed25519 2024-05-27 [SC]
      KEYID2
uid           [ultimate] Alexis Purslane (New software forge signing key) <alexispurslane@pm.me>
```

I'm using distrobox-assemble, so I can show you exactly how my distrobox is set up:

```toml
[rust-latest]
additional_packages="libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-net-dev libfreetype-dev glslang-dev glslang-tools libcurl4-openssl-dev valgrind renderdoc"
image=mcr.microsoft.com/devcontainers/rust:latest
init=false
nvidia=true
pull=true
root=false
replace=true
start_now=true
additional_flags="--cap-add=SYS_PTRACE --ulimit core=-1"
volume="/var/home/linuxbrew:/var/home/linuxbrew"
```

And I haven't done anything special/weird with the host's gpg configuration or anything either.

Even more strangely it seems that the distrobox cannot even find its *own* keys:
```bash
@rust-latest /d/var/home/alexispurslane λ gpg --list-keys
/var/home/alexispurslane/.gnupg/pubring.kbx
-------------------------------------------
pub   rsa3072 2024-05-27 [SC]
      KEYID3
uid           [ unknown] Alexis Purslane (Stuck in distrobox key) <alexispurslane@pm.me>

@rust-latest /d/var/home/alexispurslane λ gpg --delete-secret-keys KEYID3
gpg (GnuPG) 2.2.40; Copyright (C) 2022 g10 Code GmbH
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gpg: key "KEYID3" not found: Not found
gpg: KEYID3: delete key failed: Not found
@rust-latest /d/var/home/alexispurslane λ gpg --delete-keys KEYID3
gpg (GnuPG) 2.2.40; Copyright (C) 2022 g10 Code GmbH
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gpg: key "KEYID3" not found: Not found
gpg: KEYID3: delete key failed: Not found
@rust-latest /d/var/home/alexispurslane λ 
````

I would very much like to be able to sign commits from inside these distroboxes, so if you could please assist that'd be great!
