### DISCUSSION TITLE
Setting Time Zone in Container

### DISCUSSION THREAD

**Discussion by jgarte** [89luca89/distrobox#1686] [Q&A]
Hi should the timezone of the distrobox be set as an `additional_flags` or somewhere else?

```toml
[container-name]
additional_flags="--tz=America/New_York"
# or
additional_flags="-v /etc/localtime:/etc/localtime:ro"
```
